//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"ApplicationName\": \"Report Server\",\r\n    \"IncomingDirectory\":\"C:\\\\ReportJs" +
            "ons\",\r\n    \"PolFrequencyInSec\":\"1\",\r\n    \"ControlExtension\":\"ok\",\r\n    \"ReportEx" +
            "tension\":\"rpt.json\"\r\n}")]
        public string AppSettingsJson {
            get {
                return ((string)(this["AppSettingsJson"]));
            }
            set {
                this["AppSettingsJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""ReportName"":""Medlab.Clinical.AnalysisReport"",""ReportDatabaseId"":1},{""ReportName"":""Medlab.DoATemplateOne"",""ReportDatabaseId"":2},{""ReportName"":""Medlab.DoATemplate"",""ReportDatabaseId"":0},{""ReportName"":""Medlab.AnalyserGeneratedReportOne"",""ReportDatabaseId"":2}]")]
        public string ReportConfig {
            get {
                return ((string)(this["ReportConfig"]));
            }
            set {
                this["ReportConfig"] = value;
            }
        }
    }
}
